### ISSUE TITLE
Multiworld Support

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/AncientRPG#11]
I have all classes available only in one world.

- If a player choose a class
- then he goes in a world where this class is disabled
- he logs out
- he logs in

the class is lost, the player will go back to the default class

**Comment by FroznMine** [comment]
Das muss noch ausprobiert werden, bevor Multiworld veröffentlicht wird. Sonst ist das ja noch kein richtiger Fix^^

**Comment by FroznMine** [comment]
Wurde gefixt.
