### ISSUE TITLE
AddGlobalVariable not work

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/AncientRPG#142]
AddGlobalVariable does not add any persistent variable

Example:

SpellPart1
active
AddGlobalVariable, testG
Wait, 50
var testG = 5

SpellPart2
active
if, testG == 5
SendMessage, Player, It Works!
endif
else
SendMessage, Player, Nope.
endelse

--

On a side note, what is the method to add player names to Global Variables? I believe Pylamo had said %P% or %N% or something similar in the past.

**Comment by FroznMine** [comment]
Wenn es wirklich so ist, ist es auch für die nachfolgenden Tickets das gleiche: Sollte schnell gefixt werden. Mach ich glaube noch vor Rüstungs Fix, weil das wahrscheinlich schnell geht und wenn nicht unterbreche ich es nach ner Woche. Wir sollten bloß versuchen die User zufrieden zu stellen, denn was grad nicht geht sollte möglichst schnell weg, dann ist man erstmal wieder beruhigt^^

**Comment by MysticCity** [comment]
ist nur 1 user ^^ aber wenns schnell geht wieso nicht

**Comment by FroznMine** [comment]
Ist kein Fehler des Systems sondern des Nutzers. Name der Variable muss angegeben werden.

**Comment by MysticCity** [comment]
ja hattest ja schon drauf geantwortet

**Comment by FroznMine** [comment]
Wollte es nur noch mal hier stehen haben^^
