### ISSUE TITLE
How damage reduction works? 

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/AncientRPG#16]
I cant seem to work out how damage reducion in armor takes place, my diamond armor reduction values add up to 80% (default values of each peice) and zombies are set to do 150 damage, yet when i let one attack me it was doing 6 damage a hit rather than 30 damage a hit, from somewhere an extra 14% of damage reduction was appearing as far as i could see, i tested again making the damage ruction come to 50% total but again i got odd results getting 15 damage a hit this time which would be a 90% reduction in damage. so really i just dont think i understand how damage reduction is applied, could someone please explain it to me as i cant go ahead creating my classes and spells unless i know how this works for balence.

Kommentar dazu:

I am also interested in the results of this, as when changing the damage reduction percentage it appears not to effect ingame at all. For example putting all armour slots as 0% it still seems to do the same as normal.

    EDIT 

Did some testing and it appears, that the AncientRpg armour modifiers do take affect, but Minecraft overrides these in the final calculation of health.

For example, with diamond armour set to reduce damage by 50% in the config. A mob which is set as 20 is reported to do 10 damage, but health is reduced by only 3. In other words; when armour is involved vanilla damage is used.

Joa das war ein problem das mal da ist und mal nicht...^^
Je nach Build den man nimmt.
Normal sollte man einstellen können wieviel % reduziert wird.

**Comment by FroznMine** [comment]
Ist mir als ich mich an das Problem gemacht habe aufgefallen. Dadurch, dass ich jetzt über einen Trick die Rüstung von MC nicht zerstören lasse, gelten auch nur noch die Veränderungen durch AncientRPG :D
