### ISSUE TITLE
Haltbarkeit

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/AncientRPG#25]
Nun auch mal ein reiner von mir ^^
Einer von denen die ich halt noch vergessen habe.
Wollte er euch mal einbauen.

Eine Möglichkeit einzustellen wieviel haltbarkeit Rüstung hat.

**Comment by FroznMine** [comment]
9 days ago unassigned :D Wie siehts aus @ibornlp ? Schon was bei rausgekommen? Sonst mach ich das jetzt^^

**Comment by MysticCity** [comment]
iborn ist raus weil ers nciht hinbekommen hat und sich auch ncith wirklich gemeldet hat

**Comment by FroznMine** [comment]
Can't you hear the sarcasm :smiley: Das da nichts kam hab ich auch gemerkt, aber vielleicht hat er ja still und heimlich was gemacht^^

**Comment by MysticCity** [comment]
nein hat er nicht ich texte ja ab und zu mal mit ihm so alle 3 monate ^^
