### ISSUE TITLE
Instant Armor destroied 

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/AncientRPG#58]
Hello, i have a Problem with the Configs

The Armors going with 2 hits instant down!

How can i fixx that ?

------------------

Hallo, ich habe ein Problem mit den Einstellungen.
Und zwar geht die Rüstung nach ca 2 Schlägen kaputt.
Egal welche Rüstung und nur die Rüstungen. Wie kann ich das beheben?

**Comment by FroznMine** [comment]
Mach ich mich jetzt dran^^
