### ISSUE TITLE
multivers

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/AncientRPG#9]
What steps will reproduce the problem?
1. open HPConfig, XPConfig file
2. edit the parameter   HPSystem/XPsystem enabled world
3. restart the server

That parameter in the config file retruns blank!!!!

What is the expected output? What do you see instead?
no-one

Problem:
Normal kann man das komplette system für jede welt an und aus machen in der config.
Also Klassen,Monsterhp..... eben jede config.
Diese Option funktioniert halt nicht, somit kann es passieren das gleich noch ein oder 2 dieser berichte kommen, da ich sie einfach vom alten sys kopiere.

**Comment by FroznMine** [comment]
Das müsste aber gehen. Das resetten haben wir jetzt weg oder?
